version: "3"

services:
  # BigData3 - Spark model-training
  submit:
    build: ./batch-model-training
    image: model-training:latest
    container_name: submit
    environment:
      HDFS_URL: hdfs://namenode:9000
      APP_ARGS_CSV_FILE_PATH: /big-data/data.csv
      SPARK_MASTER_NAME: spark-master
      INDEXERS_PATH: /big-data/indexers/
      PIPELINE_PATH: /big-data/pipelines/
      MODEL_PATH: /big-data/model/
      DESCRIPTION_MODEL_PATH: /big-data/description_model/
      SPARK_MASTER_PORT: 7077
      SPARK_APPLICATION_ARGS: ""
      ENABLE_INIT_DAEMON: "false"